### ISSUE TITLE
Module just loading

### ISSUE THREAD

**Issue by Starplayer84** [ethanpartida/MMM-MyStudyLife#5]
Hey i installed your module reacently and it just shows as loading. Read the other post about this problem but can´t find any mistace i made...already tried your config just with my code and a reinstall...
Do you see any mistace I made in my config or know any other reason why my module will not load?

Greetings from Germany

![MMM-MyStudyLife_Config](https://user-images.githubusercontent.com/45743084/88440645-ee3c1380-ce0e-11ea-9aa7-9bd3f517e37d.PNG)

**Comment by ethanpartida** [comment]
Hi Starplayer,
Thanks for trying out my module, I'm glad to hear my code is officially international. You need to have the classes object correspond to your classes in myStudyLife. Currently it looks like you have my example schedule in the classes object. So you will have to rewrite the object to coincide with your schedule. Let me know if that doesn't work/need help doing that.

Best,
Ethan

**Comment by Starplayer84** [comment]
Hey Ethan,
oh okay that solves some of my confusion :D
The problem is we do not have any classes right now because we are more or less in our holidays (just have to do our exams) so i do not have any classes in MyStudyLife, just my exams.
If i understand this right the classes config is not allowed to be blank right? Or can the module show holidays too and just the exams without turning the schedule off in the config file?

Oh an thanks for your fast respond! Have a great weekend!

**Comment by Starplayer84** [comment]
Oh new update, after i changed the classes config and implemented my holiday into MyStudyLife the modules shows everything!
Wow it looks great, think it works now :D 

I will close this for now :)

**Comment by thinsey** [comment]
Hi, I am having the exact same problem currently. It just says "loading". I have matched the class names in the file to what is in the app. Does the array for the days also have to match perfectly or just the object names? Some of my 'classes' don't have days because I am using them basically as to do lists as well.
